### ISSUE TITLE
Error running PTVL on Kodi 19 tvOS 14.2

### ISSUE THREAD

**Issue by jhays** [PseudoTV/PseudoTV_Live#19]
Trying to run PTVL on Kodi 19.0-Alpha3 on an Apple TV running tvOS 14.2

Install seems like it worked, as I now see PTVL in my add-ons list. But attempting to launch it, or launch the channel config, result in a Kodi error alert that suggests checking the log. 

Pulled the log off my Apple TV- attached here. 
[kodi.log](https://github.com/PseudoTV/PseudoTV_Live/files/5541202/kodi.log)

A couple spots that stood out:

> 2020-11-13 21:03:24.367 T:269690   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: module 'os' has no attribute 'waitpid'
                                                   Traceback (most recent call last):
                                                     File "/private/var/mobile/Containers/Data/Application/94A8483C-96A2-42F6-80D9-5773817DB755/Library/Caches/Kodi/addons/plugin.video.pseudotv.live/service.py", line 20, in <module>
                                                       from resources.lib.globals     import *
                                                     File "/private/var/mobile/Containers/Data/Application/94A8483C-96A2-42F6-80D9-5773817DB755/Library/Caches/Kodi/addons/plugin.video.pseudotv.live/resources/lib/globals.py", line 21, in <module>
                                                       import os, sys, re, platform, subprocess, struct, shutil, traceback, threading
                                                     File "/private/var/containers/Bundle/Application/92F3B3AE-7028-4C6E-89B0-812A33DC5DC9/Kodi.app/Frameworks/lib/python3.8/subprocess.py", line 684, in <module>
                                                       class Popen(object):
                                                     File "/private/var/containers/Bundle/Application/92F3B3AE-7028-4C6E-89B0-812A33DC5DC9/Kodi.app/Frameworks/lib/python3.8/subprocess.py", line 1728, in Popen
                                                       def _internal_poll(self, _deadstate=None, _waitpid=os.waitpid,
                                                   AttributeError: module 'os' has no attribute 'waitpid'
                                                   -->End of Python script error report<--

>2020-11-13 21:03:56.431 T:269881   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: module 'os' has no attribute 'waitpid'
                                                   Traceback (most recent call last):
                                                     File "/private/var/mobile/Containers/Data/Application/94A8483C-96A2-42F6-80D9-5773817DB755/Library/Caches/Kodi/addons/plugin.video.pseudotv.live//manager.py", line 20, in <module>
                                                       from resources.lib.globals     import *
                                                     File "/private/var/mobile/Containers/Data/Application/94A8483C-96A2-42F6-80D9-5773817DB755/Library/Caches/Kodi/addons/plugin.video.pseudotv.live/resources/lib/globals.py", line 21, in <module>
                                                       import os, sys, re, platform, subprocess, struct, shutil, traceback, threading
                                                     File "/private/var/containers/Bundle/Application/92F3B3AE-7028-4C6E-89B0-812A33DC5DC9/Kodi.app/Frameworks/lib/python3.8/subprocess.py", line 684, in <module>
                                                       class Popen(object):
                                                     File "/private/var/containers/Bundle/Application/92F3B3AE-7028-4C6E-89B0-812A33DC5DC9/Kodi.app/Frameworks/lib/python3.8/subprocess.py", line 1728, in Popen
                                                       def _internal_poll(self, _deadstate=None, _waitpid=os.waitpid,
                                                   AttributeError: module 'os' has no attribute 'waitpid'
                                                   -->End of Python script error report<--

Any ideas? 
Let me know if there is any further info I can provide. 
Thanks.

**Comment by Lunatixz** [comment]
looks like an issue with the python interpreter and its built-in modules. Make sure you installed http://mirrors.kodi.tv/snapshots/darwin/tvos/org.xbmc.kodi-tvos_19.0-0~a3-tvos.deb?https=1

If you are still having issues you'll have to post a ticket at xbmc/xbmc with your log attached. The issue is with import os.waitpid 'AttributeError: module 'os' has no attribute 'waitpid'

**Comment by jhays** [comment]
I tested with 19a3 and 19b1, both have the same result. I filed an issue on xbmc/xbmc and was informed the following:

> likely it's because tvos doesn't have the ability to fork a process.

I'm guessing that means I'm out of luck for ptvl tvOS. bummer!

**Comment by Lunatixz** [comment]
I'll look for a workaround...

**Comment by jhays** [comment]
Much appreciated. Let me know there's any further way I can help or test anything.

**Comment by jhays** [comment]
FWIW, looks like someone over at the xbmc is still looking into the issue.

https://github.com/xbmc/xbmc/issues/18820

**Comment by Lunatixz** [comment]
I believe all workarounds to your issue was solved in v.0.2.3g... let me know if you're still encountering errors.

**Comment by jhays** [comment]
Thanks for the update. I did a quick test this morning after doing a full clean, and then a full delete / reinstall of the plugin to be sure. 

One thing I'm confused on is how to launch the plugin. If I select it from my Kodi home screen, it just shows a menu with the "Utilities" item. I can select that and see a few options such as the clean, or launch the settings and then access the channel manager. But I can't figure out how to launch PTVL.

If I drill into My Addons, then select PTVL, I get the add on info where I can view info and update / delete. This view has an option to "Open" the plugin, but selecting that also just opens the menu with the "Utilities" item. 

I have already opened the PTVL settings and channel manager and configured two custom channels to start testing with, so I don't think its an issue of having no channels.

Is there something I'm misunderstanding about how to launch/use this newer version, or is this a separate issue? 

I can do further testing tonight and grab a log file if that is helpful. 

Thanks- I really appreciate the support.

**Comment by jhays** [comment]
I did some testing on Kodi 19b1 on macOS, it's faster for me to test and access the log file. 

I'm getting the same result as I was on tvOS- launching the plugin just opens a menu with one item "Utilities". I can select that and see the options: 

- Delete [M3U/XMLTV/Genre]
- Clean Start, Delete [Channels/Settings/M3U/XMLTV/Genre]
- Reconfigure PVR IPTV...
- Force PVR IPTV Simple Client to reload
- Open Settings
- Parse Kodi Library

But I can't seem to "launch" PTVL to see channels / EPG. Is there something I'm missing? I'll add a log file here in case that reveals anything. 

LMK if you'd prefer a new issue for this, or if there's any other info I can provide. 

[kodi.old.log](https://github.com/PseudoTV/PseudoTV_Live/files/5638433/kodi.old.log)
