### ISSUE TITLE
Error attempting to add Channel

### ISSUE THREAD

**Issue by JGrummell** [PseudoTV/PseudoTV_Live#20]
Hi I came across the following error in my lo when attempting to add a new channel through my configuration. I did this by selecting addon, then configure option on the left side.  Now attempting to add a new channel by selecing a video playlist results in a loading animation that never completes.

Just wanted to pass it along. All the same, I am really glad to be trying out the new version!
2021-04-17 19:03:31.510 T:4844    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'str' object has no attribute 'get'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\James\AppData\Roaming\Kodi\addons\plugin.video.pseudotv.live\service.py", line 23, in <module>
                                                       if __name__ == '__main__': Service().run()
                                                     File "C:\Users\James\AppData\Roaming\Kodi\addons\plugin.video.pseudotv.live\resources\lib\service.py", line 482, in run
                                                       elif self.chkInfo(): continue # aggressive polling required (bypass waitForAbort)!
                                                     File "C:\Users\James\AppData\Roaming\Kodi\addons\plugin.video.pseudotv.live\resources\lib\service.py", line 425, in chkInfo
                                                       return fillInfoMonitor()
                                                     File "C:\Users\James\AppData\Roaming\Kodi\addons\plugin.video.pseudotv.live\resources\lib\globals.py", line 794, in fillInfoMonitor
                                                       montiorList = list(filter(lambda k:k.get('label') != '', getInfoMonitor()))
                                                     File "C:\Users\James\AppData\Roaming\Kodi\addons\plugin.video.pseudotv.live\resources\lib\globals.py", line 794, in <lambda>
                                                       montiorList = list(filter(lambda k:k.get('label') != '', getInfoMonitor()))
                                                   AttributeError: 'str' object has no attribute 'get'
                                                   -->End of Python script error report<--
                                                   
2021-04-17 19:03:31.510 T:4844     INFO <general>: CPythonInvoker(3, C:\Users\James\AppData\Roaming\Kodi\addons\plugin.video.pseudotv.live\service.py): waiting on thread 11220
2021-04-17 19:03:37.566 T:4844     INFO <general>: CPythonInvoker(3, C:\Users\James\AppData\Roaming\Kodi\addons\plugin.video.pseudotv.live\service.py): waiting on thread 9644

**Comment by JGrummell** [comment]
It also may have something to do with some of the video files scraping no video duration like the half episodes of gummi bears. The file has a duration and kodi shows a duration but I know classic pseudo had problems with video files scraped with no duration. Seems like the playlists I use for channels that hang and fail to post to the channel list are the ones that have videos with this scenario.

**Comment by Lunatixz** [comment]
THX for the info, should be fixed now...

**Comment by JGrummell** [comment]
No problem! ;)
