### ISSUE TITLE
New issue on loading

### ISSUE THREAD

**Issue by JGrummell** [PseudoTV/PseudoTV_Live#23]
I do not see others posting here so if this isn't your preferred way of getting feedback I apologize and can adapt.  Just wanted to pass along the error message to help.

`2021-04-22 21:24:48.991 T:15192   ERROR <general>: plugin.video.pseudotv.live-0.2.8o-XMLTV: getEndtimes, Failed! max() arg is an empty sequence
                                                   Traceback (most recent call last):
                                                     File "C:\Users\James\AppData\Roaming\Kodi\addons\plugin.video.pseudotv.live\resources\lib\parser.py", line 600, in getEndtimes
                                                       stopDate = max([strpTime(program['stop'], DTFORMAT).timetuple() for program in programmes if program['channel'] == channel['id']])
                                                   ValueError: max() arg is an empty sequence
                                                   
2021-04-22 21:24:48.993 T:15192   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'XMLTV' object has no attribute 'xmltv'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\James\AppData\Roaming\Kodi\addons\plugin.video.pseudotv.live\resources\lib\parser.py", line 600, in getEndtimes
                                                       stopDate = max([strpTime(program['stop'], DTFORMAT).timetuple() for program in programmes if program['channel'] == channel['id']])
                                                   ValueError: max() arg is an empty sequence
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "C:\Users\James\AppData\Roaming\Kodi\addons\plugin.video.pseudotv.live\service.py", line 23, in <module>
                                                       if __name__ == '__main__': Service().run()
                                                     File "C:\Users\James\AppData\Roaming\Kodi\addons\plugin.video.pseudotv.live\resources\lib\service.py", line 550, in run
                                                       self.chkUpdate()
                                                     File "C:\Users\James\AppData\Roaming\Kodi\addons\plugin.video.pseudotv.live\resources\lib\service.py", line 505, in chkUpdate
                                                       return self.updateChannels()
                                                     File "C:\Users\James\AppData\Roaming\Kodi\addons\plugin.video.pseudotv.live\resources\lib\service.py", line 510, in updateChannels
                                                       if self.myBuilder.buildService():
                                                     File "C:\Users\James\AppData\Roaming\Kodi\addons\plugin.video.pseudotv.live\resources\lib\builder.py", line 97, in buildService
                                                       endTimes          = self.writer.getChannelEndtimes()
                                                     File "C:\Users\James\AppData\Roaming\Kodi\addons\plugin.video.pseudotv.live\resources\lib\parser.py", line 86, in getChannelEndtimes
                                                       return self.xmltv.getEndtimes()
                                                     File "C:\Users\James\AppData\Roaming\Kodi\addons\plugin.video.pseudotv.live\resources\lib\parser.py", line 606, in getEndtimes
                                                       self.xmltv.removeChannel(channel)
                                                   AttributeError: 'XMLTV' object has no attribute 'xmltv'
                                                   -->End of Python script error report<--`

**Comment by Lunatixz** [comment]
Please supply full logs posted on https://paste.kodi.tv/

**Comment by Lunatixz** [comment]
BTW you are not running the latest version.
