### ISSUE TITLE
toggleOnNext, failed! 'title'

### ISSUE THREAD

**Issue by jaredkotoff** [PseudoTV/PseudoTV_Live#42]
main error:
```bash
   error <general>: plugin.video.pseudotv.live-0.4.0b-Overlay: toggleOnNext, failed! 'title'
                    Traceback (most recent call last):
                      File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.pseudotv.live/resources/lib/overlay.py", line 312, in toggleOnNext
                        onNow    = '%son %s'%('%s %s'%(nowItem['title'],'- %s'%(nowItem['episodename']) if nextitem['episodename'] else ''), chname)
                                                       ~~~~~~~^^^^^^^^^
                    KeyError: 'title'
```

```bash
    info <general>: Instancing CRendererMediaCodecSurface
    info <general>: CRendererMediaCodecSurface::Configure
    info <general>: Loading skin file: VideoFullScreen.xml, load type: KEEP_IN_MEMORY
 warning <general>: OutputPicture - timeout waiting for buffer
   error <general>: CMediaCodecVideoBuffer::ReleaseOutputBuffer error in render(false)
   error <general>: CMediaCodecVideoBuffer::ReleaseOutputBuffer error in render(true)
   error <general>: CMediaCodecVideoBuffer::ReleaseOutputBuffer error in render(false)
    info <general>: Skipped 1 duplicate messages..
   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                     - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                    Error Type: <class 'TypeError'>
                    Error Contents: not all arguments converted during string formatting
                    Traceback (most recent call last):
                      File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.pseudotv.live/resources/lib/service.py", line 71, in onAVStarted
                        if self.isPseudoTV: self._onPlay()
                                            ^^^^^^^^^^^^^^
                      File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.pseudotv.live/resources/lib/service.py", line 146, in _onPlay
                        forceBrute()
                      File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.pseudotv.live/resources/lib/globals.py", line 617, in forceBrute
                        if DIALOG.yesnoDialog('%s\n%s'%((LANGUAGE(32129)%(xbmcaddon.Addon(PVR_CLIENT).getAddonInfo('name'))),msg)):
                                                         ~~~~~~~~~~~~~~~^^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                    TypeError: not all arguments converted during string formatting
                    -->End of Python script error report<--


   error <general>: Unable to lookup host: 'folder.jpg'
   error <general>: NFS: Failed to mount nfs share:  (nfs_mount_async failed. Failed to start connection. )
   error <general>: Unable to lookup host: 'folder.jpg'
    info <general>: Loading skin file: DialogTextViewer.xml, load type: KEEP_IN_MEMORY
    info <general>: ProcessDecoderOutput: Changed max allowed Out-Of-Sync value to 23 ms due self-learning
    info <general>: NFS is idle. Closing the remaining connections.

    info <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - LoadPlayList Playlist Loaded - 4 (ms)
    info <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - LoadPlayList - Loaded 20 channels.
    info <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - LoadPlayList - Loaded 7 channel groups.
    info <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - LoadPlayList - Loaded 1 providers.
    info <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - LoadPlayList - Loaded 0 media items.
    info <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - LoadChannelEpgs - Loaded '20' EPG channels.
    info <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - LoadEpgEntries - Loaded '0' EPG entries.
    info <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - LoadGenres - Loaded 312 genres
    info <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - LoadEPG - EPG Loaded - 144 (ms)
    info <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - LoadChannelEpgs - Loaded '20' EPG channels.
    info <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - LoadEpgEntries - Loaded '501' EPG entries.
    info <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - LoadGenres - Loaded 312 genres
    info <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - LoadEPG - EPG Loaded - 148 (ms)
   error <general>: plugin.video.pseudotv.live-0.4.0b-Overlay: toggleOnNext, failed! 'title'
                    Traceback (most recent call last):
                      File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.pseudotv.live/resources/lib/overlay.py", line 312, in toggleOnNext
                        onNow    = '%son %s'%('%s %s'%(nowItem['title'],'- %s'%(nowItem['episodename']) if nextitem['episodename'] else ''), chname)
                                                       ~~~~~~~^^^^^^^^^
                    KeyError: 'title'

    info <general>: CVideoPlayerAudio::Process - stream stalled
    info <general>: Process - eof reading from demuxer
    info <general>: CVideoPlayer::OnExit()
    info <general>: VideoPlayer: eof, waiting for queues to empty
    info <general>: Closing stream player 1
    info <general>: CDVDMessageQueue(audio)::WaitUntilEmpty
    info <general>: Waiting for audio thread to exit
    info <general>: thread end: CVideoPlayerAudio::OnExit()
    info <general>: Closing audio device
    info <general>: Deleting audio codec
    info <general>: Closing stream player 2
    info <general>: CDVDMessageQueue(video)::WaitUntilEmpty
    info <general>: waiting for video thread to exit
    info <general>: thread end: video_thread
    info <general>: deleting video codec
    info <general>: Closing stream player 3
    info <general>: CActiveAESink::OpenSink - initialize sink
    info <general>: Trying to open: samplerate: 44100, channelMask: 12, encoding: 4
    info <general>: Minimum size we need for stream: 33960 Bytes
    info <general>: Audiotrack buffer params are: period time = 48.129 ms, period size = 16980 bytes, num periods = 4
    info <general>: Created Audiotrackbuffer with playing time of 192.517007 ms min buffer size: 67920 bytes
    info <general>: CVideoPlayer::CloseFile()
    info <general>: VideoPlayer: waiting for threads to exit
    info <general>: VideoPlayer: finished waiting
    info <general>: CVideoPlayer::CloseFile()
    info <general>: VideoPlayer: waiting for threads to exit
    info <general>: VideoPlayer: finished waiting
    info <general>: CAESinkAUDIOTRACK::Initializing with: m_sampleRate: 44100 format: AE_FMT_FLOAT (AE) method: PCM stream-type: PCM-STREAM min_buffer_size: 67920 m_frames: 2122 m_frameSize: 8 channels: 2
```

Seen in the logs

**Smartphone (please complete the following information):**
 - Device: Nvidia Shield
 - OS: Android 
 - Version: 11
 - Kodi v20.1

**Comment by Lunatixz** [comment]
Can I see more of this log? Missing some entries that could help debug the issue. THX

**Comment by jaredkotoff** [comment]
@Lunatixz I updated original post with more of the log. Does this help?

**Comment by Lunatixz** [comment]
Sorry, I'd need a full log... I have to trace where the error started prior to generating an exception.
