### ISSUE TITLE
Contents: not all arguments converted during string formatting

### ISSUE THREAD

**Issue by jaredkotoff** [PseudoTV/PseudoTV_Live#44]
```bash
 error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: not all arguments converted during string formatting
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.pseudotv.live/resources/lib/service.py", line 71, in onAVStarted
                                                       if self.isPseudoTV: self._onPlay()
                                                                           ^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.pseudotv.live/resources/lib/service.py", line 146, in _onPlay
                                                       forceBrute()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.pseudotv.live/resources/lib/globals.py", line 617, in forceBrute
                                                       if DIALOG.yesnoDialog('%s\n%s'%((LANGUAGE(32129)%(xbmcaddon.Addon(PVR_CLIENT).getAddonInfo('name'))),msg)):
                                                                                        ~~~~~~~~~~~~~~~^^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                   TypeError: not all arguments converted during string formatting
                                                   -->End of Python script error report<--
```

Seen in the logs.
When I start a channel and have error popups turned on, I see this is getting thrown

**Smartphone (please complete the following information):**
 - Device: Nvidia Shield
 - OS: Android
 - Version: 11.0.0
 - Kodi v20.1.0

**Comment by Lunatixz** [comment]
THX again... I really appreciate it! should be fixed in v.0.4.0f
