### ISSUE TITLE
Error on latest build. Addon won't run. 

### ISSUE THREAD

**Issue by loggio** [PseudoTV/PseudoTV_Live#62]
I did a full fresh install as things weren't working well lately.

Deleted all addon_data folder relating to iptv and pseudotv. 
Deleted the addon from addon folder. 

Rebooted
Re-installed PseudoTV from addon browser. 

I get an error "pseudoTV Live error check log for details" 

Here's the error in log file:

2024-12-21 21:44:26.852 T:5409    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'UnboundLocalError'>
                                                   Error Contents: cannot access local variable 'error' where it is not associated with a value
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.pseudotv.live/resources/lib/utilities.py", line 269, in <module>
                                                       if __name__ == '__main__': Utilities(sys.argv).run()
                                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.pseudotv.live/resources/lib/utilities.py", line 225, in run
                                                       self.openChannelManager()
                                                     File "/storage/.kodi/addons/plugin.video.pseudotv.live/resources/lib/utilities.py", line 133, in openChannelManager
                                                       chmanager = Manager(MANAGER_XML, ADDON_PATH, "default", channel=chnum)
                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.pseudotv.live/resources/lib/manager.py", line 57, in __init__
                                                       self.resources      = Resources(self.jsonRPC)
                                                                             ^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.pseudotv.live/resources/lib/resources.py", line 35, in __init__
                                                       self.baseURL    = jsonRPC.buildWebBase()
                                                                         ^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.pseudotv.live/resources/lib/cache.py", line 38, in wrapper
                                                       return method_class.cache.set(cacheName.lower(), method(*args, **kwargs), checksum, expiration, json_data)
                                                                                                        ^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.pseudotv.live/resources/lib/jsonrpc.py", line 511, in buildWebBase
                                                       for setting in self.getSetting('control','services'):
                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.pseudotv.live/resources/lib/jsonrpc.py", line 164, in getSetting
                                                       if cache: return self.cacheJSON(param).get('result',{}).get('settings',[])
                                                                        ^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.pseudotv.live/resources/lib/jsonrpc.py", line 76, in cacheJSON
                                                       if cacheResponse.get('result',{}): self.cache.set(cacheName, cacheResponse, checksum=checksum, expiration=life, json_data=True)
                                                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.pseudotv.live/resources/lib/cache.py", line 80, in set
                                                       self.cache.set(self.getname(name),value,checksum,expiration,json_data)
                                                     File "/storage/.kodi/addons/script.module.simplecache/lib/simplecache.py", line 86, in set
                                                       self._set_db_cache(endpoint, checksum, expires, data, json_data)
                                                     File "/storage/.kodi/addons/script.module.simplecache/lib/simplecache.py", line 157, in _set_db_cache
                                                       self._execute_sql(query, (endpoint, expires, data, checksum))
                                                     File "/storage/.kodi/addons/script.module.simplecache/lib/simplecache.py", line 252, in _execute_sql
                                                       self._log_msg("_database ERROR ! -- %s" % str(error), xbmc.LOGWARNING)
                                                                                                     ^^^^^
                                                   UnboundLocalError: cannot access local variable 'error' where it is not associated with a value
                                                   -->End of Python script error report<--

**Comment by loggio** [comment]
Fresh install of libreelec fixed it. Must have broken my system along the way.
